# Generated by Django 4.2.30 on 2026-06-05 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0002_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='summary_unlocks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paper',
            name='summary_views',
            field=models.IntegerField(default=0),
        ),
    ]
